-- Move the dense recall lane from OpenAI text-embedding-3-small (1536) to
-- Voyage voyage-4-large (1024).
--
-- WHY the existing vectors are discarded rather than converted: they cannot be
-- converted. An OpenAI vector and a Voyage vector are coordinates in different
-- spaces, so a cosine score between them is noise -- not a weak match, and
-- indistinguishable from one. Keeping them would leave the lane returning
-- confident nonsense into the LLM's context, which is worse than returning
-- nothing. They are nulled here and regenerated by deploy/backfill_voyage.py.
--
-- ORDER MATTERS: the index goes first (it is built on the old width), then the
-- data is cleared (ALTER TYPE cannot reinterpret 1536-wide rows as 1024), then
-- the column is narrowed, then the index is rebuilt.
--
-- BETWEEN THIS MIGRATION AND THE BACKFILL, dense recall contributes nothing.
-- That is survivable, not broken: vector_store's lanes are guarded by
-- `embedding IS NOT NULL`, so FTS and speaker recall keep serving through the
-- window and RRF simply fuses two lanes instead of three.

BEGIN;

DROP INDEX IF EXISTS idx_memories_embedding;

UPDATE memories SET embedding = NULL WHERE embedding IS NOT NULL;

ALTER TABLE memories ALTER COLUMN embedding TYPE vector(1024);

-- lists=1 matches the pre-migration index; at this row count ivfflat wants a
-- single list, and a mismatch here silently degrades recall quality rather
-- than erroring.
CREATE INDEX idx_memories_embedding
    ON memories USING ivfflat (embedding vector_cosine_ops) WITH (lists = 1);

COMMIT;
